services:
  dummy_wca:
    image: maxidragon/dummy-wca:main
    container_name: dummy-wca
    ports:
      - 3001:3000
    build:
      dockerfile: Dockerfile
      context: ./
    restart: unless-stopped
